sudo: required
services:
  - docker

before_install:
  - docker build -t christopheredrian/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true christopheredrian/docker-react npm run test -- --coverage

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-728534676224"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY